force-app/main/default/objects/ApprovalProcess__c/ApprovalProcess__c.object-meta.xml
<CustomObject>
    <description
	>Este objeto mantiene el control de aprobación para cambios que se llevarán a cabo de forma masiva en distintos objetos.</description>
    <label>Proceso de aprobación</label>
    <nameField>
        <displayFormat>AP{00000000}</displayFormat>
        <label>Número de aprobación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procesos de aprobación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expediente de proyecto</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Procesos de aprobación</relationshipLabel>
    <relationshipName>ApprovalProcesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Tipo_de_Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Ingreso__c</fullName>
    <description
	>Tipo de Ingreso de expediente de proyecto, se usa en plantillas de correo</description>
    <formula>TEXT(Opportunity__r.Tipo_de_Ingreso__c)</formula>
    <inlineHelpText
	>Tipo de Ingreso de expediente de proyecto, se usa en plantillas de correo</inlineHelpText>
    <label>Tipo de Ingreso</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/RGU_Change_to_approve__c.object-meta.xml
<CustomObject>
    <label>Referencia Elara por aprobar</label>
    <nameField>
        <displayFormat>RGUC-{0000000}</displayFormat>
        <label>RGU Change to approve</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referencias Elara por aprobar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process__c</fullName>
    <label>Proceso de Aprobacion</label>
    <referenceTo>ApprovalProcess__c</referenceTo>
    <relationshipName>RGU_Changes_to_approve</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Banda__c.field-meta.xml
<CustomField>
    <fullName>Banda__c</fullName>
    <label>Banda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Banda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/BWBajadaKbps__c.field-meta.xml
<CustomField>
    <fullName>BWBajadaKbps__c</fullName>
    <label>BWBajadaKbps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/BWSubidaKbps__c.field-meta.xml
<CustomField>
    <fullName>BWSubidaKbps__c</fullName>
    <label>BWSubidaKbps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Cap_Fap_GB__c.field-meta.xml
<CustomField>
    <fullName>Cap_Fap_GB__c</fullName>
    <label>Cap Fap GB</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Categoria_Unidad_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Unidad_de_Negocio__c</fullName>
    <label>Categoría por Unidad de Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categoria_por_Unidad_de_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Conceptos_por_categor_a__c.field-meta.xml
<CustomField>
    <fullName>Conceptos_por_categor_a__c</fullName>
    <label>Conceptos por categoría</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Conceptos_por_categoria</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Direccin_del_sitio__c.field-meta.xml
<CustomField>
    <fullName>Direccin_del_sitio__c</fullName>
    <label>Dirección del sitio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/EQUIPO_FINAL__c.field-meta.xml
<CustomField>
    <fullName>EQUIPO_FINAL__c</fullName>
    <label>EQUIPO FINAL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGENCIA</fullName>
            </value>
            <value>
                <fullName>FONCOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Esquema__c.field-meta.xml
<CustomField>
    <fullName>Esquema__c</fullName>
    <label>Esquema VSAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Esquema_VSAT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/FECHA_DE_BAJA_TMX_RURAL__c.field-meta.xml
<CustomField>
    <fullName>FECHA_DE_BAJA_TMX_RURAL__c</fullName>
    <label>FECHA DE BAJA TMX RURAL</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Fecha_de_emisin_IOM__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emisin_IOM__c</fullName>
    <label>Fecha de emisión IOM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Fecha_Solicitud_de_Cancelacion_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Solicitud_de_Cancelacion_Cliente__c</fullName>
    <label>Fecha Solicitud de Cancelacion Cliente</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Folio_IOM__c.field-meta.xml
<CustomField>
    <fullName>Folio_IOM__c</fullName>
    <label>Folio IOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Id_Compra__c.field-meta.xml
<CustomField>
    <fullName>Id_Compra__c</fullName>
    <label>Id Orden de Compra / Pedido TMX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Id_del_componente_Contratacin_IOM__c.field-meta.xml
<CustomField>
    <fullName>Id_del_componente_Contratacin_IOM__c</fullName>
    <label>Id del componente - Contratación IOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Id_del_componente_Renta_IOM__c.field-meta.xml
<CustomField>
    <fullName>Id_del_componente_Renta_IOM__c</fullName>
    <label>Id del componente - Renta IOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Lugar__c.field-meta.xml
<CustomField>
    <fullName>Lugar__c</fullName>
    <label>Lugar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lugar</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Nmero_de_parte_Contratacin_IOM__c.field-meta.xml
<CustomField>
    <fullName>Nmero_de_parte_Contratacin_IOM__c</fullName>
    <label>Número de parte - Contratación IOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Nmero_de_parte_Renta_IOM__c.field-meta.xml
<CustomField>
    <fullName>Nmero_de_parte_Renta_IOM__c</fullName>
    <label>Número de parte - Renta IOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Nmero_de_sitio_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>Nmero_de_sitio_del_cliente__c</fullName>
    <label>Número de sitio del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Nombre_de_sitio__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_sitio__c</fullName>
    <label>Nombre de sitio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Numero_de_lineas__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_lineas__c</fullName>
    <label>Numero de lineas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Numero_Sitio__c.field-meta.xml
<CustomField>
    <fullName>Numero_Sitio__c</fullName>
    <label>Numero Sitio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Orden_de_Aprovisionamiento_IOM_TMX__c.field-meta.xml
<CustomField>
    <fullName>Orden_de_Aprovisionamiento_IOM_TMX__c</fullName>
    <label>Orden de Aprovisionamiento IOM TMX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Paquete_KA__c.field-meta.xml
<CustomField>
    <fullName>Paquete_KA__c</fullName>
    <label>Paquete KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Paquete_KA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Referencia_Elara_Personalizada__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Elara_Personalizada__c</fullName>
    <label>Referencia Elara Personalizada</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio de conectividad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Servicio_de_conectividad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Soporte_para_pago_del_servicio__c.field-meta.xml
<CustomField>
    <fullName>Soporte_para_pago_del_servicio__c</fullName>
    <label>Soporte para pago del servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Soporte_para_pago_del_servicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/SS_DW__c.field-meta.xml
<CustomField>
    <fullName>SS_DW__c</fullName>
    <label>SS DW</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/SS_UP__c.field-meta.xml
<CustomField>
    <fullName>SS_UP__c</fullName>
    <label>SS UP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Status_COS__c.field-meta.xml
<CustomField>
    <fullName>Status_COS__c</fullName>
    <label>Status COS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Actualización</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Desactivado</fullName>
            </value>
            <value>
                <fullName>Desinstalado</fullName>
            </value>
            <value>
                <fullName>Instalado</fullName>
            </value>
            <value>
                <fullName>Por Instalar</fullName>
            </value>
            <value>
                <fullName>Reemplazo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Status_Reconocido_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Status_Reconocido_Cliente__c</fullName>
    <label>Status Reconocido Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Desactivado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Tipo_de_Enlace__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Enlace__c</fullName>
    <label>Arquitectura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Arquitectura</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Tipo_de_Ingreso__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Ingreso__c</fullName>
    <label>Tipo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Ingreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Tipo_de_servicio_IOM__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_servicio_IOM__c</fullName>
    <label>Tipo de servicio IOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RPV RESPALDO SATELITAL</fullName>
            </value>
            <value>
                <fullName>RPV RESPALDO SATELITAL NUBE</fullName>
            </value>
            <value>
                <fullName>RPV SATELITAL</fullName>
            </value>
            <value>
                <fullName>RPV SATELITAL NUBE</fullName>
            </value>
            <value>
                <fullName>RPV TRANSACCIONAL SATELITAL</fullName>
            </value>
            <value>
                <fullName>IDE PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>IDE RESPALDO</fullName>
            </value>
            <value>
                <fullName>IDE PRINCIPAL CONTINGENCIAS</fullName>
            </value>
            <value>
                <fullName>INTERNET SATELITAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalProcessControlRGUController.cls
public with sharing class ApprovalProcessControlRGUController {
	@AuraEnabled(cacheable=true)
	public static List<RGU__c> getRelatedReferences(Id recordId) {
		try {
			ApprovalProcess__c approvalProcess = [
				SELECT id, Opportunity__c
				FROM ApprovalProcess__c
				WHERE id = :recordId
			];

			List<RGU__c> lRGUs = [
				SELECT
					Id,
					Name,
					Referencia__c,
					Nombre_de_sitio__c,
					Status_COS__c,
					Numero_Sitio__c
				FROM RGU__c
				WHERE
					NumeroDeExpedienteDeProyecto__c = :approvalProcess.Opportunity__c
			];

			return lRGUs;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static void saveRGUChangeToApprove(
		Id recordId,
		List<RGU__c> referenciasSeleccionadas
	) {
		try {
			System.debug(referenciasSeleccionadas);
			//Eliminamos los

			List<RGU_Change_to_approve__c> RGUsToApprove = [
				SELECT id
				FROM RGU_Change_to_approve__c
				WHERE Approval_Process__c = :recordId
			];

			delete RGUsToApprove;

			if (referenciasSeleccionadas.size() > 0) {
				//Obtenemos todos los campos de Referencia Elara
				SObjectType accountType = Schema.getGlobalDescribe()
					.get('RGU__C');
				Map<String, Schema.SObjectField> mfields = accountType.getDescribe()
					.fields.getMap();

				String selectSentence = '';

				for (String fieldName : mfields.keySet()) {
					selectSentence += fieldName + ',';
				}

				String whereSentence = '';

				for (RGU__c references : referenciasSeleccionadas) {
					whereSentence += '\'' + references.id + '\',';
				}

				//Hacemos select all de rgu, de los que se seleccionó para dar de baja el servicio
				List<RGU__c> lRGUs = Database.query(
					'select ' +
					selectSentence.Substring(0, selectSentence.length() - 1) +
					' from RGU__c where id in (' +
					whereSentence.Substring(0, whereSentence.length() - 1) +
					')'
				);

				//Generamos los objetos clones de las referencias de los que van a entrar en proceso de aprobación
				List<RGU_Change_to_approve__c> lRGUToApprove = new List<RGU_Change_to_approve__c>();

				for (RGU__c referenciaOriginal : lRGUs) {
					RGU_Change_to_approve__c RGUToApprove = new RGU_Change_to_approve__c(
						Referencia_Elara_Personalizada__c = referenciaOriginal.Referencia_Elara_Personalizada__c,
						Nombre_de_sitio__c = referenciaOriginal.Nombre_de_sitio__c,
						Nmero_de_sitio_del_cliente__c = referenciaOriginal.N_mero_de_sitio_del_cliente__c,
						Numero_Sitio__c = referenciaOriginal.Numero_Sitio__c,
						Lugar__c = referenciaOriginal.Lugar__c,
						Direccin_del_sitio__c = referenciaOriginal.Direcci_n_del_sitio__c,
						Soporte_para_pago_del_servicio__c = referenciaOriginal.Soporte_para_pago_del_servicio__c,
						Status_Reconocido_Cliente__c = referenciaOriginal.Status_Reconocido_Cliente__c,
						Id_Compra__c = referenciaOriginal.Id_Compra__c,
						Fecha_Solicitud_de_Cancelacion_Cliente__c = referenciaOriginal.Fecha_Solicitud_de_Cancelacion_Cliente__c,
						Tipo_de_Ingreso__c = referenciaOriginal.Tipo_de_Ingreso__c,
						Categoria_Unidad_de_Negocio__c = referenciaOriginal.Categoria_Unidad_Negocio__c,
						Conceptos_por_categor_a__c = referenciaOriginal.Concepto_Categoria__c,
						Servicio__c = referenciaOriginal.Servicio__c,
						Tipo_de_Enlace__c = referenciaOriginal.Tipo_de_Enlace__c,
						Esquema__c = referenciaOriginal.Esquema__c,
						Banda__c = referenciaOriginal.Banda__c,
						BWBajadaKbps__c = referenciaOriginal.BWBajadaKbps__c,
						BWSubidaKbps__c = referenciaOriginal.BWSubidaKbps__c,
						SS_DW__c = referenciaOriginal.SS_DW__c,
						SS_UP__c = referenciaOriginal.SS_UP__c,
						Paquete_KA__c = referenciaOriginal.Paquete_KA__c,
						Numero_de_lineas__c = referenciaOriginal.Numero_de_lineas__c,
						Cap_Fap_GB__c = referenciaOriginal.Cap_Fap_GB__c,
						Orden_de_Aprovisionamiento_IOM_TMX__c = referenciaOriginal.Orden_de_Aprovisionamiento_IOM_TMX__c,
						Folio_IOM__c = referenciaOriginal.Folio_IOM__c,
						Fecha_de_emisin_IOM__c = referenciaOriginal.Fecha_de_emisi_n_IOM__c,
						Tipo_de_servicio_IOM__c = referenciaOriginal.Tipo_de_servicio_IOM__c,
						Nmero_de_parte_Contratacin_IOM__c = referenciaOriginal.N_mero_de_parte_Contrataci_n_IOM__c,
						Id_del_componente_Contratacin_IOM__c = referenciaOriginal.Id_del_componente_Contrataci_n_IOM__c,
						Nmero_de_parte_Renta_IOM__c = referenciaOriginal.N_mero_de_parte_Renta_IOM__c,
						Id_del_componente_Renta_IOM__c = referenciaOriginal.Id_del_componente_Renta_IOM__c,
						EQUIPO_FINAL__c = referenciaOriginal.EQUIPO_FINAL__c,
						FECHA_DE_BAJA_TMX_RURAL__c = referenciaOriginal.FECHA_DE_BAJA_TMX_RURAL__c,
						FASE_TMX_RURAL__c = referenciaOriginal.FASE_TMX_RURAL__c,
						FECHA_VALIDACION_IVR_TMX__c = referenciaOriginal.FECHA_VALIDACION_IVR_TMX__c,
						NUEVA_DIVISION_TMX_RURAL__c = referenciaOriginal.NUEVA_DIVISION_TMX_RURAL__c,
						ESTATUS_SITIO_TMX_RURAL__c = referenciaOriginal.ESTATUS_SITIO_TMX_RURAL__c,
						DIVISION_TMX_RURAL__c = referenciaOriginal.DIVISION_TMX_RURAL__c,
						NUMERO_DE_LINEAS_MIGRADAS_ACTIVAS__c = referenciaOriginal.NUMERO_DE_LINEAS_MIGRADAS_ACTIVAS__c,
						ESTATUS_FACTURACION__c = referenciaOriginal.ESTATUS_FACTURACION__c,
						LINEAS_MIGRADAS_ACTIVAS__c = referenciaOriginal.LINEAS_MIGRADAS_ACTIVAS__c,
						OBSERVACIONES_TMX_RURAL__c = referenciaOriginal.OBSERVACIONES_TMX_RURAL__c,
						Approval_Process__c = recordId,
						Referencia_Elara_Original__c = referenciaOriginal.Id
					);
					lRGUToApprove.add(RGUToApprove);
				}

				insert lRGUToApprove;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static List<Id> getRGUToApprove(Id recordId) {
		List<Id> lSelectedRows = new List<Id>();

		for (RGU_Change_to_approve__c rguToApprove : [
			SELECT Referencia_Elara_Original__c
			FROM RGU_Change_to_approve__c
			WHERE Approval_Process__c = :recordId
		]) {
			lSelectedRows.add(rguToApprove.Referencia_Elara_Original__c);
		}
		return lSelectedRows;
	}
}