force-app/main/default/objects/ApprovalProcess__c/ApprovalProcess__c.object-meta.xml
<CustomObject>
    <description
	>Este objeto mantiene el control de aprobación para cambios que se llevarán a cabo de forma masiva en distintos objetos.</description>
    <label>Proceso de aprobación</label>
    <nameField>
        <displayFormat>AP{00000000}</displayFormat>
        <label>Número de aprobación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procesos de aprobación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcess__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Acción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalAction</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Cantidad_de_facturas_pendientes__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_facturas_pendientes__c</fullName>
    <description>- Facturas pendientes de pago</description>
    <label>Cantidad de facturas pendientes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/CAPEX__c.field-meta.xml
<CustomField>
    <fullName>CAPEX__c</fullName>
    <inlineHelpText>Documentar el CAPEX que se requeriría para los proyectos.</inlineHelpText>
    <label>CAPEX</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Costos_por_cubrir__c.field-meta.xml
<CustomField>
    <fullName>Costos_por_cubrir__c</fullName>
    <description>- Costos por cubrir para llegar a la rentabilidad indicada del proyecto</description>
    <label>Costos por cubrir</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>Describe brevemente el proceso de aprobación para que puedas encontrarlo fácilmente.</description>
    <externalId>true</externalId>
    <label>Detalle</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Divisa_CAPEX__c.field-meta.xml
<CustomField>
    <fullName>Divisa_CAPEX__c</fullName>
    <label>Divisa CAPEX</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/EBIT__c.field-meta.xml
<CustomField>
    <fullName>EBIT__c</fullName>
    <description>EBIT = Cash Flow - Depreciación</description>
    <inlineHelpText>EBIT = Cash Flow - Depreciación</inlineHelpText>
    <label>EBIT</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/EBITDA__c.field-meta.xml
<CustomField>
    <fullName>EBITDA__c</fullName>
    <description>EBITDA = Margen Bruto - Gastos</description>
    <inlineHelpText>EBITDA = Margen Bruto - Gastos</inlineHelpText>
    <label>EBITDA</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Ingresos_por_cubrir__c.field-meta.xml
<CustomField>
    <fullName>Ingresos_por_cubrir__c</fullName>
    <description>- Ingresos por cubrir para llegar a la rentabilidad indicada del proyecto</description>
    <label>Ingresos por cubrir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Margen_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Margen_Bruto__c</fullName>
    <description>Margen Bruto = Ingresos - costos directos</description>
    <inlineHelpText>Margen Bruto = Ingresos - costos directos</inlineHelpText>
    <label>Margen Bruto</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <description>Describe brevemente el proceso de aprobación para que puedas encontrarlo fácilmente.</description>
    <externalId>true</externalId>
    <label>Nombre</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/NombreDelProyecto__c.field-meta.xml
<CustomField>
    <fullName>NombreDelProyecto__c</fullName>
    <description>Nombre del Proyecto del Expediente Proyecto, se usa para plantillas de correo</description>
    <formula>Opportunity__r.NombreDelProyecto__r.Nombre_Completo__c</formula>
    <inlineHelpText>Nombre del Proyecto del Expediente Proyecto, se usa para plantillas de correo</inlineHelpText>
    <label>NombreDelProyecto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expediente de proyecto</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Procesos de aprobación</relationshipLabel>
    <relationshipName>ApprovalProcesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Par_metros_de_rentabilidad__c.field-meta.xml
<CustomField>
    <fullName>Par_metros_de_rentabilidad__c</fullName>
    <description
	>Se elige de una lista el cumplimiento de la políticas de rentabilidad</description>
    <inlineHelpText
	>Indicar si cumple con las políticas de rentabilidad.</inlineHelpText>
    <label>Parámetros de rentabilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Aplica</fullName>
                <default>true</default>
                <label>No Aplica</label>
            </value>
            <value>
                <fullName>Cumple</fullName>
            </value>
            <value>
                <fullName>No Cumple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Payback__c.field-meta.xml
<CustomField>
    <fullName>Payback__c</fullName>
    <description>PAYBACK = Meses para recuperar el capital inicial</description>
    <inlineHelpText
	>PAYBACK = Meses para recuperar el capital inicial</inlineHelpText>
    <label>Payback</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Proveedor_es_y_banda_del_SE__c.field-meta.xml
<CustomField>
    <fullName>Proveedor_es_y_banda_del_SE__c</fullName>
    <label>Proveedor(es) y banda del SE</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <description>ROI = Retorno sobre la inversión, cuánto ganará la empresa en el tiempo.</description>
    <inlineHelpText>ROI = Retorno sobre la inversión, cuánto ganará la empresa en el tiempo.</inlineHelpText>
    <label>ROI</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Saldo_cubierto_a_la_fecha__c.field-meta.xml
<CustomField>
    <fullName>Saldo_cubierto_a_la_fecha__c</fullName>
    <description>(Ingresos generados)</description>
    <label>Saldo cubierto a la fecha</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Saldo_pendiente_de_pago__c.field-meta.xml
<CustomField>
    <fullName>Saldo_pendiente_de_pago__c</fullName>
    <label>Saldo pendiente de pago</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Etapas del proceso de aprobación para cambios.</description>
    <inlineHelpText>Etapas del proceso de aprobación para cambios.</inlineHelpText>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Solicitado</fullName>
            </value>
            <value>
                <fullName>Documentación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/TIR__c.field-meta.xml
<CustomField>
    <fullName>TIR__c</fullName>
    <description
	>TIR = Tasa Interna de Retorno, mide la viabilidad de un proyecto determinando la rentabilidad de los cobros y pagos actualizados generados por una inversión</description>
    <inlineHelpText
	>TIR = Tasa Interna de Retorno, mide la viabilidad de un proyecto determinando la rentabilidad de los cobros y pagos actualizados generados por una inversión</inlineHelpText>
    <label>TIR</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ApprovalProcess__c/fields/Vigencia_contrato_proveedor_satelital__c.field-meta.xml
<CustomField>
    <fullName>Vigencia_contrato_proveedor_satelital__c</fullName>
    <description>- Vigencia del contrato con el operador satelital</description>
    <label>Vigencia contrato proveedor satelital</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/RGU_Change_to_approve__c.object-meta.xml
<CustomObject>
    <label>Referencia Elara por aprobar</label>
    <nameField>
        <displayFormat>RGUC-{0000000}</displayFormat>
        <label>RGU Change to approve</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referencias Elara por aprobar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process__c</fullName>
    <label>Proceso de Aprobacion</label>
    <referenceTo>ApprovalProcess__c</referenceTo>
    <relationshipName>RGU_Changes_to_approve</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Banda__c.field-meta.xml
<CustomField>
    <fullName>Banda__c</fullName>
    <label>Banda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Banda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/BWBajadaKbps__c.field-meta.xml
<CustomField>
    <fullName>BWBajadaKbps__c</fullName>
    <label>BWBajadaKbps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/BWSubidaKbps__c.field-meta.xml
<CustomField>
    <fullName>BWSubidaKbps__c</fullName>
    <label>BWSubidaKbps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Categoria_Unidad_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Unidad_de_Negocio__c</fullName>
    <label>Categoría por Unidad de Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categoria_por_Unidad_de_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Esquema__c.field-meta.xml
<CustomField>
    <fullName>Esquema__c</fullName>
    <label>Esquema VSAT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Esquema_VSAT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Lugar__c.field-meta.xml
<CustomField>
    <fullName>Lugar__c</fullName>
    <label>Lugar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lugar</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Nombre_de_sitio__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_sitio__c</fullName>
    <label>Nombre de sitio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Referencia_Elara__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Elara__c</fullName>
    <label>Referencia Elara</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio de conectividad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Servicio_de_conectividad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/SS_DW__c.field-meta.xml
<CustomField>
    <fullName>SS_DW__c</fullName>
    <label>SS DW</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/SS_UP__c.field-meta.xml
<CustomField>
    <fullName>SS_UP__c</fullName>
    <label>SS UP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Tipo_de_Enlace__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Enlace__c</fullName>
    <label>Arquitectura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Arquitectura</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Tipo_de_sitio_por_aprobar__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_sitio_por_aprobar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de sitio por aprobar</label>
    <referenceTo>TipoDeSitioPorAprobar__c</referenceTo>
    <relationshipLabel>Referencias Elara por aprobar</relationshipLabel>
    <relationshipName>Referencias_Elara_por_aprobar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Unidad_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Unidad_de_Negocio__c</fullName>
    <label>Unidad de Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unidad_de_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalAction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Baja definitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelación de referencias</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio - Altas crecimiento orgánico</fullName>
    </customValue>
    <customValue>
        <fullName>Cambio - Actualización</fullName>
    </customValue>
    <customValue>
        <fullName>Incremento</fullName>
        <isActive>false</isActive>
        <label>Incremento</label>
    </customValue>
    <customValue>
        <fullName>Decremento</fullName>
        <isActive>false</isActive>
        <label>Decremento</label>
    </customValue>
    <customValue>
        <fullName>Reubicación</fullName>
        <isActive>false</isActive>
        <label>Reubicación</label>
    </customValue>
    <customValue>
        <fullName>Migración de plataforma satelital</fullName>
        <isActive>false</isActive>
        <label>Migración de plataforma satelital</label>
    </customValue>
    <customValue>
        <fullName>Soporte Remoto</fullName>
        <isActive>false</isActive>
        <label>Soporte Remoto</label>
    </customValue>
    <customValue>
        <fullName>Ingenieria de campo</fullName>
        <isActive>false</isActive>
        <label>Ingenieria de campo</label>
    </customValue>
    <customValue>
        <fullName>Adecuaciones especiales</fullName>
        <isActive>false</isActive>
        <label>Adecuaciones especiales</label>
    </customValue>
    <customValue>
        <fullName>Suspensión del ingreso</fullName>
        <isActive>false</isActive>
        <label>Suspensión del ingreso</label>
    </customValue>
    <customValue>
        <fullName>Finalización de ingreso</fullName>
        <isActive>false</isActive>
        <label>Finalización de ingreso</label>
    </customValue>
    <customValue>
        <fullName>Finalización del ingreso</fullName>
        <isActive>false</isActive>
        <label>Finalización del ingreso</label>
    </customValue>
    <customValue>
        <fullName>Migración</fullName>
        <isActive>false</isActive>
        <label>Migración</label>
    </customValue>
    <customValue>
        <fullName>Cambio - Reactivación del servicio</fullName>
        <isActive>false</isActive>
        <label>Cambio - Reactivación del servicio</label>
    </customValue>
    <customValue>
        <fullName>Cambio - Suspensión del servicio</fullName>
        <isActive>false</isActive>
        <label>Cambio - Suspensión del servicio</label>
    </customValue>
    <customValue>
        <fullName>Cambio - Reemplazo RE</fullName>
        <isActive>false</isActive>
        <label>Cambio - Reemplazo RE</label>
    </customValue>
    <customValue>
        <fullName>Cambio - Transferencia RE</fullName>
        <isActive>false</isActive>
        <label>Cambio - Transferencia RE</label>
    </customValue>
    <masterLabel>Apobración Acción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrganicGrowthApprovalProcessTest.cls
@isTest
public with sharing class OrganicGrowthApprovalProcessTest {
	@TestSetup
	static void makeData() {
		Test.setMock(HttpCalloutMock.class, new COSAPI_MockTesting());

		OpportunityTriggerSettings.setCurrentActiveValue(false);
		AccountTriggerSettings.setCurrentActiveValue(false);
		TipoDeSitioTriggerSettings.setCurrentActiveValue(false);
		RGUTriggerSettings.setCurrentActiveValue(false);

		Account testAccount = new Account(
			Name = 'Cuenta A',
			Razon_Social__c = 'CUENTA SA DE CV A',
			Industry = 'CAT',
			OrigenDeLaCuenta__c = 'Cliente Actual',
			RFC__c = 'POT151008L69',
			BillingPostalCode = '86037',
			ID_Fiscal__c = '',
			Tiene_Contratos_Activos__c = true
		);

		insert testAccount;

		Proyecto__c testProject = new Proyecto__c(
			Name = 'Test project with a long name',
			Unidad_de_Negocio__c = 'CONECTIVIDAD',
			Categoria_Unidad_Negocio__c = 'VSAT'
		);

		insert testProject;

		Pricebook2 testPricebook = new Pricebook2(
			Name = 'testStandardListPrice',
			IsActive = true
		);

		insert testPricebook;

		Product2 testProduct = new Product2(
			Name = 'Test product',
			IsActive = true,
			ConceptoFacturacion__c = 'PRODUCTO DE PRUEBA PT'
		);

		insert testProduct;

		PricebookEntry testEntry = new PricebookEntry(
			Product2Id = testProduct.Id,
			Pricebook2Id = Test.getStandardPricebookId(),
			IsActive = true,
			UnitPrice = 500
		);

		insert testEntry;

		Opportunity testOpportunity = new Opportunity(
			Sector_Comercial__c = 'Privado',
			StageName = 'Cierre',
			CloseDate = System.today(),
			Name = 'a',
			AccountId = testAccount.Id,
			NombreDelProyecto__c = testProject.Id,
			Pricebook2Id = Test.getStandardPricebookId()
		);

		insert testOpportunity;

		TipoDeSitio__c testSite = new TipoDeSitio__c(
			NumeroDeExpedienteDeProyecto__c = testOpportunity.Id,
			Nombre_Completo__c = 'testing site',
			NumeroDeSitios__c = 10
		);

		TipoDeSitioTriggerSettings.insertWithoutTriggers(
			new List<TipoDeSitio__c>{ testSite }
		);

		RGU__c testReference = new RGU__c(
			Tipo_de_sitio__c = testSite.Id,
			NumeroDeExpedienteDeProyecto__c = testOpportunity.Id
		);

		insert testReference;

		System.debug(testReference);

		List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();

		OpportunityLineItem testLineItemSite = new OpportunityLineItem(
			OpportunityId = testOpportunity.Id,
			Referencia_Elara__c = testReference.Id,
			PricebookEntryId = testEntry.Id,
			Tipo_de_sitio__c = testSite.Id,
			UnitPrice = 1000,
			UnitPrice__c = 1000,
			Quantity = 2,
			Forma_de_Cobro__c = 'Mensual',
			Fecha_Inicio_Ingreso__c = Date.today(),
			Fecha_Fin_Ingreso__c = Date.today(),
			Plazo__c = 3,
			Divisa_de_Cotizacion__c = 'USD',
			Linea_de_Negocio__c = 'Conectividad'
		);

		OpportunityLineItem testLineItemReference = new OpportunityLineItem(
			OpportunityId = testOpportunity.Id,
			PricebookEntryId = testEntry.Id,
			Referencia_Elara__c = testReference.Id,
			UnitPrice = 1000,
			UnitPrice__c = 1000,
			Quantity = 2,
			Forma_de_Cobro__c = 'Mensual',
			Fecha_Inicio_Ingreso__c = Date.today(),
			Plazo__c = 3,
			Divisa_de_Cotizacion__c = 'USD',
			Linea_de_Negocio__c = 'Conectividad'
		);

		lineItems.add(testLineItemSite);
		lineItems.add(testLineItemReference);

		OpportunityLineItemTriggerSettings.insertWithoutTriggers(lineItems);

		ApprovalProcess__c approval = new ApprovalProcess__c(
			Nombre__c = 'Proceso de prueba',
			Detail__c = 'Detalle',
			Action__c = 'Cambio - Altas crecimiento orgánico',
			Opportunity__c = testOpportunity.Id,
			Stage__c = 'Iniciado'
		);

		insert approval;

		TipoDeSitioPorAprobar__c tipoDeSitio = new TipoDeSitioPorAprobar__c(
			Lugar__c = 'AEROPUERTO',
			ID_Orden_de_compra_cliente__c = 'Id Orden de Compra',
			NumeroDeSitios__c = 1,
			Esquema_comercial__c = 'Esquema comercial',
			Fase__c = 2,
			Tipo_de_Configuracion__c = 'ESTÁNDAR',
			Tipo_de_solicitud__c = 'STD',
			Proceso_de_aprobacion__c = approval.id,
			Categoria_Unidad_Negocio__c = 'VSAT',
			Servicio__c = 'ISE',
			Tipo_de_Enlace__c = 'PRIMARIO',
			Esquema__c = 'FIJO',
			Banda__c = 'KU',
			BWBajadaKbps__c = 1024,
			BWSubidaKbps__c = 1024,
			SS_DW__c = 10,
			SS_UP__c = 10
		);

		TipoDeSitioPorAprobarTriggerSettings.insertWithoutTriggers(
			new List<TipoDeSitioPorAprobar__c>{ tipoDeSitio }
		);

		RGU_Change_to_approve__c reference = new RGU_Change_to_approve__c();
		reference.Tipo_de_sitio_por_aprobar__c = tipoDeSitio.Id;
		reference.Nombre_de_sitio__c = 'SITIO 1';
		reference.Categoria_Unidad_de_Negocio__c = tipoDeSitio.Categoria_Unidad_Negocio__c;
		reference.Servicio__c = tipoDeSitio.Servicio__c;
		reference.Tipo_de_Enlace__c = tipoDeSitio.Tipo_de_Enlace__c;
		reference.Esquema__c = tipoDeSitio.Esquema__c;
		reference.Banda__c = tipoDeSitio.Banda__c;
		reference.BWBajadaKbps__c = tipoDeSitio.BWBajadaKbps__c;
		reference.SS_DW__c = tipoDeSitio.SS_DW__c;
		reference.BWSubidaKbps__c = tipoDeSitio.BWSubidaKbps__c;
		reference.SS_UP__c = tipoDeSitio.SS_UP__c;
		reference.Approval_Process__c = tipoDeSitio.Proceso_de_aprobacion__c;
		reference.Lugar__c = tipoDeSitio.Lugar__c;
		reference.Tipo_de_sitio_por_aprobar__c = tipoDeSitio.id;

		RGU_Change_to_approveTriggerSettings.insertWithoutTriggers(
			new List<RGU_Change_to_approve__c>{ reference }
		);

		testProduct = new Product2(
			Name = 'Test product',
			IsActive = true,
			ConceptoFacturacion__c = 'INSTALACION DE EQUIPO VSAT PARA PRESTACIÓN DE SERVICIO DE CONEXIÓN SATELITAL'
		);

		insert testProduct;

		PricebookEntry pricebookEntry = new PricebookEntry(
			Product2Id = testProduct.Id,
			Pricebook2Id = Test.getStandardPricebookId(),
			IsActive = true,
			UnitPrice = 500
		);

		insert pricebookEntry;

		OpportunityItemConsent__c oli = new OpportunityItemConsent__c(
			Proceso_de_aprobacion__c = approval.id,
			PricebookEntryId__c = pricebookEntry.Id,
			Referencia_Elara_por_aprobar__c = reference.Id,
			UnitPrice__c = 1000,
			Quantity__c = 2,
			Fecha_Inicio_de_Ingreso__c = Date.today(),
			Forma_de_Cobro__c = 'Mensual',
			Plazo__c = 1
		);

		insert oli;
	}

	@isTest
	static void TestingOrganicGrowthApprovalProcessTest() {
		Test.setMock(HttpCalloutMock.class, new COSAPI_MockTesting());
		ApprovalProcess__c approval = [
			SELECT
				id,
				Stage__c,
				Saldo_cubierto_a_la_fecha__c,
				Saldo_pendiente_de_pago__c,
				Cantidad_de_facturas_pendientes__c,
				Margen_Bruto__c,
				CAPEX__c,
				Divisa_CAPEX__c,
				EBITDA__c,
				EBIT__c,
				Payback__c,
				Par_metros_de_rentabilidad__c,
				ROI__c,
				TIR__c,
				Ingresos_por_cubrir__c,
				Costos_por_cubrir__c,
				Proveedor_es_y_banda_del_SE__c,
				Vigencia_contrato_proveedor_satelital__c,
				Proxima_fecha_cambio_segmento__c,
				Monto_Cambio_SE__c
			FROM ApprovalProcess__c
			LIMIT 1
		];

		OrganicGrowthApprovalProcess.validateCompleteInformation(approval);

		approval.stage__c = 'Solicitado';
		update approval;
	}

	@isTest
	static void TestingOrganicGrowthApprovalProcessApprovedTest() {
		Test.setMock(HttpCalloutMock.class, new COSAPI_MockTesting());
		ApprovalProcess__c approval = [
			SELECT
				id,
				Stage__c,
				Saldo_cubierto_a_la_fecha__c,
				Saldo_pendiente_de_pago__c,
				Cantidad_de_facturas_pendientes__c,
				Margen_Bruto__c,
				CAPEX__c,
				Divisa_CAPEX__c,
				EBITDA__c,
				EBIT__c,
				Payback__c,
				Par_metros_de_rentabilidad__c,
				ROI__c,
				TIR__c,
				Ingresos_por_cubrir__c,
				Costos_por_cubrir__c,
				Proveedor_es_y_banda_del_SE__c,
				Vigencia_contrato_proveedor_satelital__c,
				Proxima_fecha_cambio_segmento__c,
				Monto_Cambio_SE__c
			FROM ApprovalProcess__c
			LIMIT 1
		];

		approval.stage__c = 'Solicitado';
		ApprovalProcessTriggerSettings.updateWithoutTriggers(
			new List<ApprovalProcess__c>{ approval }
		);

		approval.stage__c = 'Aprobado';

		update approval;
	}

	@isTest
	public static void TestingOrganicGrowthApprovalProcessReject() {
		Test.setMock(HttpCalloutMock.class, new COSAPI_MockTesting());
		List<ApprovalProcess__c> approval = [
			SELECT
				id,
				Stage__c,
				Saldo_cubierto_a_la_fecha__c,
				Saldo_pendiente_de_pago__c,
				Cantidad_de_facturas_pendientes__c,
				Margen_Bruto__c,
				CAPEX__c,
				Divisa_CAPEX__c,
				EBITDA__c,
				EBIT__c,
				Payback__c,
				Par_metros_de_rentabilidad__c,
				ROI__c,
				TIR__c,
				Ingresos_por_cubrir__c,
				Costos_por_cubrir__c,
				Proveedor_es_y_banda_del_SE__c,
				Vigencia_contrato_proveedor_satelital__c,
				Proxima_fecha_cambio_segmento__c,
				Monto_Cambio_SE__c
			FROM ApprovalProcess__c
			LIMIT 1
		];

		List<OpportunityItemConsent__c> oli = [
			SELECT
				Proceso_de_aprobacion__c,
				PricebookEntryId__c,
				Referencia_Elara_por_aprobar__c,
				UnitPrice__c,
				Quantity__c,
				Fecha_Inicio_de_Ingreso__c,
				Fecha_Fin_Ingreso__c,
				Forma_de_Cobro__c,
				Plazo__c
			FROM OpportunityItemConsent__c
		];

		OrganicGrowthApprovalProcess.validateOpportunityLineItem(oli);

		OrganicGrowthApprovalProcess.validateConditions(approval);
	}

	@isTest
	public static void TestingOrganicGrowthApprovalRejected() {
		Test.setMock(HttpCalloutMock.class, new COSAPI_MockTesting());
		ApprovalProcess__c approval = [
			SELECT
				id,
				Stage__c,
				Saldo_cubierto_a_la_fecha__c,
				Saldo_pendiente_de_pago__c,
				Cantidad_de_facturas_pendientes__c,
				Margen_Bruto__c,
				CAPEX__c,
				Divisa_CAPEX__c,
				EBITDA__c,
				EBIT__c,
				Payback__c,
				Par_metros_de_rentabilidad__c,
				ROI__c,
				TIR__c,
				Ingresos_por_cubrir__c,
				Costos_por_cubrir__c,
				Proveedor_es_y_banda_del_SE__c,
				Vigencia_contrato_proveedor_satelital__c,
				Proxima_fecha_cambio_segmento__c,
				Monto_Cambio_SE__c
			FROM ApprovalProcess__c
			LIMIT 1
		];

		approval.stage__c = 'Solicitado';
		update approval;

		approval.stage__c = 'Rechazado';
		approval.Motivo_rechazo_o_cancelacion__c = 'Porque si';

		update approval;
	}

	@isTest
	public static void TestingValidateTipoSitio() {
		OrganicGrowthApprovalProcess.validateTiposSitio(
			new List<TipoDeSitioPorAprobar__c>{ new TipoDeSitioPorAprobar__c() }
		);

		OrganicGrowthApprovalProcess.validateTiposSitio(
			new List<TipoDeSitioPorAprobar__c>{
				new TipoDeSitioPorAprobar__c(
					Categoria_Unidad_Negocio__c = 'VSAT'
				)
			}
		);

		OrganicGrowthApprovalProcess.validateTiposSitio(
			new List<TipoDeSitioPorAprobar__c>{
				new TipoDeSitioPorAprobar__c(Banda__c = 'HTS KA')
			}
		);
	}

	@isTest
	public static void TestingValidateOlis() {
		OrganicGrowthApprovalProcess.validateOpportunityLineItem(
			new List<OpportunityItemConsent__c>{
				new OpportunityItemConsent__c()
			}
		);
	}
}