force-app/main/default/objects/RGU_Change_to_approve__c/RGU_Change_to_approve__c.object-meta.xml
<CustomObject>
    <label>Referencia Elara por aprobar</label>
    <nameField>
        <displayFormat>RGUC-{0000000}</displayFormat>
        <label>RGU Change to approve</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referencias Elara por aprobar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Referencia_Elara__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Elara__c</fullName>
    <label>Referencia Elara</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/Referencia_Elara_Original__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Elara_Original__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Es la relación con la referencia elara a la que se desea aplicar los cambios con el proceso de aprobación</description>
    <label>Referencia Elara Original</label>
    <referenceTo>RGU__c</referenceTo>
    <relationshipLabel>Referencias Elara por aprobar</relationshipLabel>
    <relationshipName>RGU_Changes_to_approve</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RGU_Change_to_approve__c/fields/VTC_Referencia_Original__c.field-meta.xml
<CustomField>
    <fullName>VTC_Referencia_Original__c</fullName>
    <label>VTC Referencia Original</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RGU_Change_to_approveAPI.cls
public with sharing class RGU_Change_to_approveAPI {
	public static void executeBeforeInsertProcess(
		TriggerParameters triggerParams
	) {
		//Convertimos los nuevos registros al tipo de Proceso de aprobacion
		List<RGU_Change_to_approve__c> lRGUToApprove = (List<RGU_Change_to_approve__c>) triggerParams.newList;

		setVTCPerRGUOriginal(lRGUToApprove);
	}

	//Establece el vtc para cada Referencia elara, es importante para poder validar si la aprobación es por comité directivo o control comercial
	@testVisible
	private static void setVTCPerRGUOriginal(
		List<RGU_Change_to_approve__c> lRGUsToChange
	) {
		//Obtenemos las id referencias Elara Originales

		List<id> idsRGUs = new List<id>();

		for (RGU_Change_to_approve__c rguToChange : lRGUsToChange) {
			idsRGUs.add(rguToChange.Referencia_Elara_Original__c);
		}

		Map<Id, List<OpportunityLineItem>> olisPerRGUs = new Map<Id, List<OpportunityLineItem>>();

		List<OpportunityLineItem> oppLineItems = [
			SELECT Id, Referencia_Elara__r.id, Partida_Ventas_MXN__c
			FROM OpportunityLineItem
			WHERE Referencia_Elara__r.id IN :idsRGUs
		];

		for (OpportunityLineItem oppLineItem : oppLineItems) {
			List<OpportunityLineItem> lOppLineItem;

			if (
				(lOppLineItem = olisPerRGUs.get(
					oppLineItem.Referencia_Elara__r.id
				)) == null
			) {
				lOppLineItem = new List<OpportunityLineItem>();
				olisPerRGUs.put(
					oppLineItem.Referencia_Elara__r.id,
					lOppLineItem
				);
			}
			lOppLineItem.add(oppLineItem);
		}

		for (RGU_Change_to_approve__c rguToChange : lRGUsToChange) {
			List<OpportunityLineItem> actualOlis = olisPerRGUs.get(
				rguToChange.Referencia_Elara_Original__c
			);
			Decimal vtcRGU = 0;
			for (OpportunityLineItem oli : actualOlis) {
				vtcRGU += oli.Partida_Ventas_MXN__c;
			}

			rguToChange.VTC_Referencia_Original__c = vtcRGU;
		}
	}
}